/**
 * PDF generation utility for reports
 * Using simple text-based PDF for now - can be enhanced with jsPDF or similar
 */

export function generateSimplePDF(title: string, content: string): string {
  // For now, return formatted text
  // In production, you would use a library like jsPDF or pdfmake
  return `
${title}
${'='.repeat(title.length)}

${content}

Generated by ChiRho Events
${new Date().toLocaleDateString()}
`.trim()
}

export function generateFinancialPDF(reportData: any, eventName: string): string {
  const content = `
FINANCIAL REPORT - ${eventName}

REVENUE SUMMARY:
  Total Revenue:    $${reportData.totalRevenue.toFixed(2)}
  Amount Paid:      $${reportData.amountPaid.toFixed(2)}
  Balance Due:      $${reportData.balanceDue.toFixed(2)}
  Overdue Balance:  $${reportData.overdueBalance.toFixed(2)}

PAYMENT METHOD BREAKDOWN:
  Credit Card (Stripe): $${reportData.paymentMethods.stripe.toFixed(2)}
  Check:                $${reportData.paymentMethods.check.toFixed(2)}
  Pending:              $${reportData.paymentMethods.pending.toFixed(2)}

REVENUE BY PARTICIPANT TYPE:
${Object.entries(reportData.byParticipantType)
  .map(([type, data]: [string, any]) =>
    `  ${type.replace(/_/g, ' ').padEnd(15)}: $${data.revenue.toFixed(2)} (${data.count} people)`
  )
  .join('\n')}

REVENUE BY HOUSING TYPE:
  On-Campus:  $${reportData.byHousingType.onCampus.revenue.toFixed(2)} (${reportData.byHousingType.onCampus.count} people)
  Off-Campus: $${reportData.byHousingType.offCampus.revenue.toFixed(2)} (${reportData.byHousingType.offCampus.count} people)
  Day Pass:   $${reportData.byHousingType.dayPass.revenue.toFixed(2)} (${reportData.byHousingType.dayPass.count} people)
`

  return generateSimplePDF(`Financial Report - ${eventName}`, content)
}

export function generateRegistrationPDF(reportData: any, eventName: string): string {
  const content = `
REGISTRATION REPORT - ${eventName}

REGISTRATION SUMMARY:
  Total Registrations:      ${reportData.totalRegistrations} people
  Group Registrations:      ${reportData.groupCount} (${reportData.groupParticipants} people)
  Individual Registrations: ${reportData.individualCount}
  Average Group Size:       ${reportData.avgGroupSize.toFixed(1)} people

DEMOGRAPHICS:
${Object.entries(reportData.demographics || {})
  .map(([type, data]: [string, any]) =>
    `  ${type.replace(/_/g, ' ').padEnd(15)}: ${data.total} (Male: ${data.male}, Female: ${data.female})`
  )
  .join('\n')}
`

  return generateSimplePDF(`Registration Report - ${eventName}`, content)
}
