ALTER TABLE events ADD COLUMN IF NOT EXISTS start_time VARCHAR(5);
ALTER TABLE events ADD COLUMN IF NOT EXISTS end_time VARCHAR(5);
ALTER TABLE event_settings ADD COLUMN IF NOT EXISTS show_event_countdown BOOLEAN DEFAULT false;
